import { defineArrayMember, defineField, defineType } from "sanity";

export const siteContent = defineType({
  name: "siteContent",
  title: "Contenido del sitio",
  type: "document",
  groups: [
    { name: "home", title: "Inicio", default: true },
    { name: "workshop", title: "El taller" },
    { name: "contact", title: "Contacto" },
  ],
  fields: [
    defineField({ name: "homeHeroKicker", title: "Texto breve", type: "localizedString", group: "home" }),
    defineField({ name: "homeHeroTitle", title: "Título principal", type: "localizedString", group: "home" }),
    defineField({ name: "homeHeroIntro", title: "Texto de portada", type: "localizedText", group: "home" }),
    defineField({ name: "homeHeroImage", title: "Imagen de portada", type: "editorialImage", group: "home" }),
    defineField({ name: "homeWorkshopTitle", title: "Título de presentación del taller", type: "localizedString", group: "home" }),
    defineField({ name: "homeStoryEyebrow", title: "Texto breve de la historia", type: "localizedString", group: "home" }),
    defineField({ name: "homeStoryTitle", title: "Título de la historia", type: "localizedString", group: "home" }),
    defineField({ name: "homeStoryBody", title: "Texto de la historia", type: "localizedText", group: "home" }),
    defineField({ name: "homeStoryImage", title: "Imagen de la historia", type: "editorialImage", group: "home" }),
    defineField({ name: "workshopTitle", title: "Título", type: "localizedString", group: "workshop" }),
    defineField({ name: "workshopIntro", title: "Introducción", type: "localizedText", group: "workshop" }),
    defineField({ name: "workshopImage", title: "Imagen del taller", type: "editorialImage", group: "workshop" }),
    defineField({ name: "workshopProcessEyebrow", title: "Texto breve del proceso", type: "localizedString", group: "workshop" }),
    defineField({ name: "workshopProcessTitle", title: "Título del proceso", type: "localizedString", group: "workshop" }),
    defineField({ name: "workshopParagraphOne", title: "Primer párrafo", type: "localizedText", group: "workshop" }),
    defineField({ name: "workshopParagraphTwo", title: "Segundo párrafo", type: "localizedText", group: "workshop" }),
    defineField({ name: "workshopStepsLabel", title: "Título de los pasos", type: "localizedString", group: "workshop" }),
    defineField({
      name: "workshopSteps",
      title: "Pasos del proceso",
      type: "array",
      of: [defineArrayMember({ type: "workshopStep" })],
      group: "workshop",
    }),
    defineField({ name: "contactTitle", title: "Título", type: "localizedString", group: "contact" }),
    defineField({ name: "contactIntro", title: "Introducción", type: "localizedText", group: "contact" }),
    defineField({ name: "contactPanelEyebrow", title: "Texto breve del panel", type: "localizedString", group: "contact" }),
    defineField({ name: "contactPanelTitle", title: "Título del panel", type: "localizedString", group: "contact" }),
    defineField({ name: "contactPanelBody", title: "Texto del panel", type: "localizedText", group: "contact" }),
    defineField({ name: "contactLinkText", title: "Texto del enlace", type: "localizedString", group: "contact" }),
    defineField({ name: "contactLinkUrl", title: "Dirección web de contacto", type: "url", group: "contact" }),
  ],
  preview: {
    prepare: () => ({ title: "Contenido del sitio" }),
  },
});